#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

## Convenience Functions

# Push any configuration changes to dotfiles repo
function push-config {
(
	if [ -z "$1" ]; then
		printf "Usage: push-config <commit-message>\n"
		return 1
	fi
	cd $ZDOTDIR/.zprezto
	if [[ ! `git status --porcelain` ]]; then
		printf "No Prezto changes\n"
	else
		printf "Committing and pushing Prezto changes...\n"
		git add -A
		git commit -m "$1"
		git push
		printf "\n"
	fi
	cd ~/.config
	if [[ ! `git status --porcelain` ]]; then
		printf "No other config changes\n"
	else
		printf "Committing and pushing config changes...\n"
		git add -A
		git commit -m "$1"
		git push
	fi
)
}
